[Federal_Single]
standard_deduction = 16100
standard_deduction_extra65 = 2000
brackets = [[0,      10],
            [12400,  12],
            [50400,  22],
            [105700, 24],
            [201775, 32],
            [256225, 35],
            [640600, 37]]
net_investment_income_threshold = 200_000

capital_gains_taxrates = [[0,        0],
               [49450,   15],
               [545500,  20]]


[Federal_MFJ]
standard_deduction = 32200
standard_deduction_extra65 = 3200
brackets = [[0,      10],
            [24800,  12],
            [100800, 22],
            [211400, 24],
            [403550, 32],
            [512450, 35],
            [768700, 37]]
net_investment_income_threshold = 250_000

capital_gains_taxrates = [[0,        0],
               [98900,   15],
               [613700,  20]]


[FPL]
fpl = [[1,	15650],
    [2,	21150],
    [3,	26650],
    [4,	32150],
    [5,	37650],
    [6,	43150],
    [7,	48650],
    [8,	54150]]

[FPL_AK]
fpl = [[1,	19550],
    [2,	26430],
    [3,	33310],
    [4,	40190],
    [5,	47070],
    [6,	53950],
    [7,	60830],
    [8,	67710]]

[FPL_HI]
fpl = [[1,	17990],
    [2,	24320],
    [3,	30650],
    [4,	36980],
    [5,	43310],
    [6,	49640],
    [7,	55970],
    [8,	62300]]
